version: "3.8"

services:

  portainer:
    # We are using the 3 free nodes business edition
    image: portainer/portainer-ee:2.26.1-alpine
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      # HTTP port for traefik internal communication
      - "9000:9000"
      # HTTPS port with self signed cert for fallback administration
      # (e.g., traefik maintenance)
      - "9443:9443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${PORTAINER_TRAEFIK_URL}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.services.frontend.loadbalancer.server.port=9000"
    networks:
      - proxy

volumes:
  portainer_data:

# Since we have different stacks for portainer and traefik
# we need to include a common network
networks:
  proxy:
    name: proxy
    external: true
